<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Child;

class ChildSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $children = [
            ['first_name' => 'MOUHAMADOU M', 'last_name' => 'CISSE', 'date_of_birth' => '2018-07-06', 'gender' => 'G', 'group_id' => 1],
            ['first_name' => 'SOKHNA .K', 'last_name' => 'DIAGNE', 'date_of_birth' => '2017-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'YANDE DIARATOULAHI', 'last_name' => 'NDOUR', 'date_of_birth' => '2017-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'FATIMA.K', 'last_name' => 'DIOUF', 'date_of_birth' => '2017-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'COUMBA', 'last_name' => 'CISSE', 'date_of_birth' => '2016-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'MOUHAMED ADAMA CISSE', 'last_name' => 'YAGUE', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 1],
            ['first_name' => 'MOUHAMED KOITA', 'last_name' => 'DIALLO', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 1],
            ['first_name' => 'MOUHAMED ABDALLAH', 'last_name' => 'NDIAYE', 'date_of_birth' => '2015-07-06', 'gender' => 'G', 'group_id' => 1],
            ['first_name' => 'MAME ANTA', 'last_name' => 'MBOW', 'date_of_birth' => '2015-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'MANDIANG', 'last_name' => 'GAYE', 'date_of_birth' => '2015-07-06', 'gender' => 'G', 'group_id' => 1],
            ['first_name' => 'NDEYE YAYE KANE', 'last_name' => 'ANNE', 'date_of_birth' => '2015-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'NDEYE BINETA.C.A', 'last_name' => 'NDOYE', 'date_of_birth' => '2014-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'IBRAHIMA SOULEYMANE', 'last_name' => 'LY', 'date_of_birth' => '2014-07-06', 'gender' => 'G', 'group_id' => 1],
            ['first_name' => 'MAME DIARRA BOUSSO', 'last_name' => 'NDIAYE', 'date_of_birth' => '2014-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'LASSY', 'last_name' => 'SALL', 'date_of_birth' => '2014-07-06', 'gender' => 'G', 'group_id' => 1],
            ['first_name' => 'ABDOURAHMANE', 'last_name' => 'BA', 'date_of_birth' => '2013-07-06', 'gender' => 'G', 'group_id' => 1],
            ['first_name' => 'MOUHAMADOU BAMBA', 'last_name' => 'SINE', 'date_of_birth' => '2013-07-06', 'gender' => 'G', 'group_id' => 1],
            ['first_name' => 'MARIAMA', 'last_name' => 'NDOYE', 'date_of_birth' => '2013-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'SEYDINA MOUHAMED', 'last_name' => 'KA', 'date_of_birth' => '2012-07-06', 'gender' => 'G', 'group_id' => 1],
            ['first_name' => 'MAREME SODA', 'last_name' => 'AW', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'AMINATA', 'last_name' => 'FALL', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'MAIMOUNA ADAMA', 'last_name' => 'BA', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'FATOU', 'last_name' => 'NDOYE', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'BASSIROU', 'last_name' => 'NDIAYE', 'date_of_birth' => '2011-07-06', 'gender' => 'G', 'group_id' => 1],
            ['first_name' => 'NDEYE AMINATA', 'last_name' => 'SARR', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'NFALLY', 'last_name' => 'SANE', 'date_of_birth' => '2014-07-06', 'gender' => 'G', 'group_id' => 1],
            ['first_name' => 'ADJI CHEIKH MAR', 'last_name' => 'DIENG', 'date_of_birth' => '2014-07-06', 'gender' => 'F', 'group_id' => 1],
            ['first_name' => 'AISSATOU', 'last_name' => 'CISSE', 'date_of_birth' => '2018-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'OUMAR BOUBOU', 'last_name' => 'BA', 'date_of_birth' => '2017-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'ADJA AMINATA SY', 'last_name' => 'DIEYE', 'date_of_birth' => '2017-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'ADJA FATOU', 'last_name' => 'DIOP', 'date_of_birth' => '2017-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'CHEIKH AHMADOU', 'last_name' => 'NDIAYE', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'ABDOULAYE NDIAYE', 'last_name' => 'GUEYE', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'NAFISSATOU KOTO', 'last_name' => 'SONKO', 'date_of_birth' => '2016-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'MOUHAMED', 'last_name' => 'DIA', 'date_of_birth' => '2015-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'CHEIKH AHMADOU B', 'last_name' => 'NDIAYE', 'date_of_birth' => '2015-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'MOUHAMMAD RACHID', 'last_name' => 'DIOP', 'date_of_birth' => '2015-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'AWANI', 'last_name' => 'DIALLO', 'date_of_birth' => '2015-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'AMINATA. B', 'last_name' => 'DIAO', 'date_of_birth' => '2014-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'ABDOULAYE MAPATE', 'last_name' => 'MBODJI', 'date_of_birth' => '2014-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'ASTOU', 'last_name' => 'MANE', 'date_of_birth' => '2014-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'ADAMA THIAM', 'last_name' => 'NDIAYE', 'date_of_birth' => '2013-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'VICENZO PIERRE', 'last_name' => 'NDIONE', 'date_of_birth' => '2013-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'ADJA NDACK', 'last_name' => 'DIEYE', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'OUMANE MALICK', 'last_name' => 'BA', 'date_of_birth' => '2012-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'ELISABETH R L M', 'last_name' => 'DOGUE', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'SEYNABOU', 'last_name' => 'SYLLA', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'KHADIJA', 'last_name' => 'TINE', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'SOKHNA MARIAMA', 'last_name' => 'MBAYE', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'MOUSSA', 'last_name' => 'THIAW', 'date_of_birth' => '2011-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'NDELLA ADAMA', 'last_name' => 'BA', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 2],
            ['first_name' => 'ALIOUNE', 'last_name' => 'NDIONE', 'date_of_birth' => '2011-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'MOUHAMED', 'last_name' => 'NDIAYE', 'date_of_birth' => '2013-07-06', 'gender' => 'G', 'group_id' => 2],
            ['first_name' => 'YAYE AMINATA', 'last_name' => 'DIENG', 'date_of_birth' => '2018-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'IDRISSA', 'last_name' => 'SANE', 'date_of_birth' => '2017-07-06', 'gender' => 'G', 'group_id' => 3],
            ['first_name' => 'PENDA SY', 'last_name' => 'VARELLE', 'date_of_birth' => '2017-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'ZINEB', 'last_name' => 'DABO', 'date_of_birth' => '2017-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'EDWIN LIONEL M', 'last_name' => 'SENE', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 3],
            ['first_name' => 'SOFIATOU', 'last_name' => 'FALL', 'date_of_birth' => '2016-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'MOUSSA', 'last_name' => 'NDOUR', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 3],
            ['first_name' => 'BINETA PENDA', 'last_name' => 'SARR', 'date_of_birth' => '2015-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'AHMADOU MBACKE MADINA', 'last_name' => 'NDIAYE', 'date_of_birth' => '2015-07-06', 'gender' => 'G', 'group_id' => 3],
            ['first_name' => 'CHEIKH SENY.M', 'last_name' => 'SOW', 'date_of_birth' => '2015-07-06', 'gender' => 'G', 'group_id' => 3],
            ['first_name' => 'MOUHAMADOU MANSOUR', 'last_name' => 'NIANG', 'date_of_birth' => '2015-07-06', 'gender' => 'G', 'group_id' => 3],
            ['first_name' => 'LALA MARIEME', 'last_name' => 'DIENE', 'date_of_birth' => '2014-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'ASSANE', 'last_name' => 'FAYE', 'date_of_birth' => '2014-07-06', 'gender' => 'G', 'group_id' => 3],
            ['first_name' => 'SOPHIE DIARRA BOUSSO', 'last_name' => 'DASILVA', 'date_of_birth' => '2014-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'MOUHAMAD', 'last_name' => 'SANKHARE', 'date_of_birth' => '2013-07-06', 'gender' => 'G', 'group_id' => 3],
            ['first_name' => 'MAME DIARRA', 'last_name' => 'NDIAYE', 'date_of_birth' => '2013-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'FATIMA', 'last_name' => 'MBAYE', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'BAYE OUSSEYNOU', 'last_name' => 'THIAM', 'date_of_birth' => '2012-07-06', 'gender' => 'G', 'group_id' => 3],
            ['first_name' => 'BADIENE MAREME', 'last_name' => 'DIOUF', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'OUMAR DIOUF', 'last_name' => 'DIANDY', 'date_of_birth' => '2012-07-06', 'gender' => 'G', 'group_id' => 3],
            ['first_name' => 'AICHA', 'last_name' => 'TOURE', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'NDEYE MARIEME', 'last_name' => 'MBODJ', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'BRIAN NICOLAS', 'last_name' => 'MALACK', 'date_of_birth' => '2011-07-06', 'gender' => 'G', 'group_id' => 3],
            ['first_name' => 'AISSATA', 'last_name' => 'SECK', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'FATOUMATA BINETOU', 'last_name' => 'KONATE', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'EL HADJI MOCTAR SIDIKI', 'last_name' => 'BOCOUM', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 3],
            ['first_name' => 'ANTA', 'last_name' => 'FAYE', 'date_of_birth' => '2013-07-06', 'gender' => 'F', 'group_id' => 3],
            ['first_name' => 'CHEIKH TIDIANE', 'last_name' => 'SALL', 'date_of_birth' => '2018-07-06', 'gender' => 'G', 'group_id' => 4],
            ['first_name' => 'ASTOU', 'last_name' => 'SARR', 'date_of_birth' => '2017-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'KHADIDIATOU DIAGNE', 'last_name' => 'DIOP', 'date_of_birth' => '2017-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'JOSEPH .R.ABDOULAYE', 'last_name' => 'LALYRE', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 4],
            ['first_name' => 'NDEYE KHADY', 'last_name' => 'SECK', 'date_of_birth' => '2016-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'FATOUMATA SALLA', 'last_name' => 'BEYE', 'date_of_birth' => '2016-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'MOUHAMED SACRIA', 'last_name' => 'GUEYE', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 4],
            ['first_name' => 'YACINE', 'last_name' => 'SARR', 'date_of_birth' => '2015-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'NDEYE CODOU', 'last_name' => 'NDIAYE', 'date_of_birth' => '2015-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'MOUHAMAD ALIOU', 'last_name' => 'NDAO', 'date_of_birth' => '2015-07-06', 'gender' => 'G', 'group_id' => 4],
            ['first_name' => 'CORNELLE ANDRE.T', 'last_name' => 'COLY', 'date_of_birth' => '2015-07-06', 'gender' => 'G', 'group_id' => 4],
            ['first_name' => 'CHEIKH M B', 'last_name' => 'KANDJI', 'date_of_birth' => '2014-07-06', 'gender' => 'G', 'group_id' => 4],
            ['first_name' => 'OUSSEYNOU', 'last_name' => 'FAYE', 'date_of_birth' => '2014-07-06', 'gender' => 'G', 'group_id' => 4],
            ['first_name' => 'ALIMATOU', 'last_name' => 'KA', 'date_of_birth' => '2014-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'FATOUMATA B', 'last_name' => 'DIOP', 'date_of_birth' => '2013-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'PAPE OUSSEYNOU', 'last_name' => 'DIOP', 'date_of_birth' => '2013-07-06', 'gender' => 'G', 'group_id' => 4],
            ['first_name' => 'GOGO BOCOUM', 'last_name' => 'NIANE', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'PAPE IBRAHIMA', 'last_name' => 'THIAW', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'FATOU', 'last_name' => 'TALL', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'KHADIDIATOU', 'last_name' => 'SIMA', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'MOUHAMED BOUBACAR NIANG', 'last_name' => 'DIOP', 'date_of_birth' => '2011-07-06', 'gender' => 'G', 'group_id' => 4],
            ['first_name' => 'SOKHNA BINETOU', 'last_name' => 'SARR', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'PAPE MAKHA OUSSEYNOU', 'last_name' => 'BATHILY', 'date_of_birth' => '2011-07-06', 'gender' => 'G', 'group_id' => 4],
            ['first_name' => 'MOUHAMED YAMAR', 'last_name' => 'FALL', 'date_of_birth' => '2011-07-06', 'gender' => 'G', 'group_id' => 4],
            ['first_name' => 'KINE SEYNABOU', 'last_name' => 'DIOP', 'date_of_birth' => '2016-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'ADJA MINGUE', 'last_name' => 'NDAO', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 4],
            ['first_name' => 'AIDA THIOFFEL', 'last_name' => 'GUEYE', 'date_of_birth' => '2018-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'FATOUMATA', 'last_name' => 'SARR', 'date_of_birth' => '2017-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'MOUHAMADOUL FATAH', 'last_name' => 'DIONE', 'date_of_birth' => '2017-07-06', 'gender' => 'G', 'group_id' => 5],
            ['first_name' => 'AMINATA GOUYE', 'last_name' => 'CISSE', 'date_of_birth' => '2016-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'KHADY', 'last_name' => 'FALL', 'date_of_birth' => '2016-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'ABOU BAILA', 'last_name' => 'DIAW', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 5],
            ['first_name' => 'MOUHAMED', 'last_name' => 'KAMISSOGO', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 5],
            ['first_name' => 'ALIMATOU', 'last_name' => 'MBAYE', 'date_of_birth' => '2015-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'MARIAMA', 'last_name' => 'NDIAYE', 'date_of_birth' => '2015-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'JULIEN BAMBA', 'last_name' => 'HUGO', 'date_of_birth' => '2015-07-06', 'gender' => 'G', 'group_id' => 5],
            ['first_name' => 'OULIMATA', 'last_name' => 'DIOP', 'date_of_birth' => '2015-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'FATIMATA', 'last_name' => 'SETTE', 'date_of_birth' => '2014-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'ALIOUNE BADARA', 'last_name' => 'BEYE', 'date_of_birth' => '2014-07-06', 'gender' => 'G', 'group_id' => 5],
            ['first_name' => 'MAMAN ALDIOUMA', 'last_name' => 'SOW', 'date_of_birth' => '2014-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'AISSATOU', 'last_name' => 'SANNEH', 'date_of_birth' => '2013-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'ABDOU AZIZ', 'last_name' => 'DIOUF', 'date_of_birth' => '2013-07-06', 'gender' => 'G', 'group_id' => 5],
            ['first_name' => 'KHOUDIA', 'last_name' => 'GUEYE', 'date_of_birth' => '2013-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'FATOU DIOP', 'last_name' => 'SALL', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'JEAN BAPTISTE', 'last_name' => 'THIARE', 'date_of_birth' => '2012-07-06', 'gender' => 'G', 'group_id' => 5],
            ['first_name' => 'KHADY', 'last_name' => 'NDIAYE', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'NDEYE ARAME', 'last_name' => 'GUEYE', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'FATOUMATA', 'last_name' => 'MAR', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'DIARRA', 'last_name' => 'NIASS', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'IBRAHIMA', 'last_name' => 'DIA', 'date_of_birth' => '2011-07-06', 'gender' => 'G', 'group_id' => 5],
            ['first_name' => 'ADJA TACKO', 'last_name' => 'FAYE', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 5],
            ['first_name' => 'AL HASSANE', 'last_name' => 'ARIS', 'date_of_birth' => '2017-07-06', 'gender' => 'G', 'group_id' => 5],
            ['first_name' => 'FALLOU STEVEN', 'last_name' => 'WRIGHT', 'date_of_birth' => '2011-07-06', 'gender' => 'G', 'group_id' => 5],
            ['first_name' => 'YACINE', 'last_name' => 'NDIAYE', 'date_of_birth' => '2018-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'AMINATA', 'last_name' => 'DIALLO', 'date_of_birth' => '2017-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'OUSMANE', 'last_name' => 'DIOUF', 'date_of_birth' => '2017-07-06', 'gender' => 'G', 'group_id' => 6],
            ['first_name' => 'AMINATA SENE', 'last_name' => 'NDIAYE', 'date_of_birth' => '2016-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'ADAMA RACINE', 'last_name' => 'NDAW', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 6],
            ['first_name' => 'COUMBA', 'last_name' => 'SECK', 'date_of_birth' => '2016-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'YOSSOUF', 'last_name' => 'DIOP', 'date_of_birth' => '2016-07-06', 'gender' => 'G', 'group_id' => 6],
            ['first_name' => 'PAPE ABDOU', 'last_name' => 'NDIAYE', 'date_of_birth' => '2015-07-06', 'gender' => 'G', 'group_id' => 6],
            ['first_name' => 'MARIEME', 'last_name' => 'SALL', 'date_of_birth' => '2015-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'KHADIDIATOU', 'last_name' => 'DIOUF', 'date_of_birth' => '2015-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'ISSEU', 'last_name' => 'CAMARA', 'date_of_birth' => '2014-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'AMADOU D', 'last_name' => 'THIOYE', 'date_of_birth' => '2014-07-06', 'gender' => 'G', 'group_id' => 6],
            ['first_name' => 'MAME DIOBA', 'last_name' => 'DEMBA', 'date_of_birth' => '2014-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'MAME MOUSSE DIOP', 'last_name' => 'SENE', 'date_of_birth' => '2014-07-06', 'gender' => 'G', 'group_id' => 6],
            ['first_name' => 'AWA', 'last_name' => 'SARR', 'date_of_birth' => '2013-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'CHEIKH AHMADOU BAMBA', 'last_name' => 'DIOP', 'date_of_birth' => '2013-07-06', 'gender' => 'G', 'group_id' => 6],
            ['first_name' => 'MOUHAMADOU', 'last_name' => 'BA', 'date_of_birth' => '2013-07-06', 'gender' => 'G', 'group_id' => 6],
            ['first_name' => 'MARIAMA', 'last_name' => 'FAYE', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'KHADI DIA', 'last_name' => 'SYLLA', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'EL HADJI BABACAR', 'last_name' => 'DIAGNE', 'date_of_birth' => '2012-07-06', 'gender' => 'G', 'group_id' => 6],
            ['first_name' => 'KHADIDIATOU NDOFFENE', 'last_name' => 'DIOUF', 'date_of_birth' => '2012-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'FATOUMATA BINETOU', 'last_name' => 'WANE', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'MOUHAMADOU ABDEL BACHIR', 'last_name' => 'SAKHO', 'date_of_birth' => '2011-07-06', 'gender' => 'G', 'group_id' => 6],
            ['first_name' => 'FATOUMATA', 'last_name' => 'KAGNY', 'date_of_birth' => '2011-07-06', 'gender' => 'F', 'group_id' => 6],
            ['first_name' => 'MOUHAMED', 'last_name' => 'SEYE', 'date_of_birth' => '2011-07-06', 'gender' => 'G', 'group_id' => 6],
            ['first_name' => 'GAMOU', 'last_name' => 'POUYE', 'date_of_birth' => '2012-07-06', 'gender' => 'G', 'group_id' => 6],
        ];

        foreach ($children as $childData) {
            Child::firstOrCreate(
                [
                    'first_name' => $childData['first_name'],
                    'last_name' => $childData['last_name'],
                ],
                [
                    'date_of_birth' => $childData['date_of_birth'],
                    'gender' => $childData['gender'],
                    'group_id' => $childData['group_id'],
                ]
            );
        }
    }
}
